package com.example.wallora.repository.collections

import com.example.wallora.R
import com.example.wallora.model.Wallpaper

object FunnyHalloweenCollection {

    val wallpapers = listOf(

        Wallpaper(
            name = "Pumpkin Party",
            image = R.drawable.halloween_fun_01,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "pumpkin",
                "ghost",
                "party",
                "dj",
                "funny",
                "cute",
                "spooky",
                "autumn",
                "night",
                "cat",
                "costume",
                "orange"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),

        Wallpaper(
            name = "Trick or Treat Cats",
            image = R.drawable.halloween_fun_02,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "cats",
                "cat",
                "kitten",
                "ghost",
                "pumpkin",
                "witch",
                "witch hat",
                "trick or treat",
                "cute",
                "funny",
                "spooky",
                "autumn",
                "night"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Skeleton Party",
            image = R.drawable.halloween_fun_03,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "skeleton",
                "funny",
                "party",
                "dance",
                "dancing",
                "pumpkin",
                "ghost",
                "cat",
                "candy",
                "trick or treat",
                "spooky",
                "cute",
                "autumn",
                "night"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Ghost Riders",
            image = R.drawable.halloween_fun_04,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "ghost",
                "ghosts",
                "riders",
                "scooter",
                "funny",
                "cute",
                "pumpkin",
                "cat",
                "black cat",
                "trick or treat",
                "party",
                "spooky",
                "autumn",
                "night"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Witch Gone Wild",
            image = R.drawable.halloween_fun_05,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "witch",
                "broom",
                "flying",
                "funny",
                "cute",
                "black cat",
                "cat",
                "candy",
                "pumpkin",
                "magic",
                "spooky",
                "autumn",
                "night",
                "haunted"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Monster Selfie",
            image = R.drawable.halloween_fun_06,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "monster",
                "monsters",
                "selfie",
                "mummy",
                "vampire",
                "frankenstein",
                "ghost",
                "pumpkin",
                "funny",
                "cute",
                "party",
                "spooky",
                "autumn",
                "night"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Monster Chase",
            image = R.drawable.halloween_fun_07,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "mummy",
                "frankenstein",
                "vampire",
                "dracula",
                "monster",
                "monsters",
                "chase",
                "running",
                "funny",
                "cute",
                "black cat",
                "pumpkin",
                "spooky",
                "autumn",
                "night"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Pumpkin Rollercoaster",
            image = R.drawable.halloween_fun_08,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "rollercoaster",
                "amusement park",
                "theme park",
                "pumpkin",
                "jack o lantern",
                "black cat",
                "ghost",
                "funny",
                "cute",
                "spooky",
                "ride",
                "autumn",
                "night",
                "full moon"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Trick or Treat Squad",
            image = R.drawable.halloween_fun_09,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "trick or treat",
                "cat",
                "kitten",
                "dog",
                "ghost",
                "pumpkin",
                "candy",
                "cute",
                "funny",
                "spooky",
                "autumn",
                "night",
                "witch",
                "full moon"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Zombie Pizza Delivery",
            image = R.drawable.halloween_fun_10,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "zombie",
                "pizza",
                "delivery",
                "scooter",
                "ghost",
                "black cat",
                "pumpkin",
                "funny",
                "cute",
                "spooky",
                "autumn",
                "night",
                "full moon",
                "village"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Halloween Bakery Disaster",
            image = R.drawable.halloween_fun_11,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "bakery",
                "skeleton",
                "ghost",
                "black cat",
                "pumpkin",
                "cupcake",
                "cookie",
                "candy",
                "funny",
                "cute",
                "spooky",
                "autumn",
                "night",
                "baking"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Halloween Moon Party",
            image = R.drawable.halloween_fun_12,
            category = "Halloween",
            tags = listOf(
                "halloween",
                "moon",
                "party",
                "dj",
                "skeleton",
                "ghost",
                "black cat",
                "pumpkin",
                "music",
                "rooftop",
                "funny",
                "cute",
                "spooky",
                "night",
                "full moon"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        )
    )
}