package com.example.wallora.repository.collections

import com.example.wallora.R
import com.example.wallora.model.Wallpaper

object RainyNightsCollection {

    val wallpapers = listOf(

        Wallpaper(
            name = "Rainy City Lights",
            image = R.drawable.rainy_nights_01,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "city",
                "lights",
                "street",
                "umbrella",
                "moon",
                "reflection",
                "wet street",
                "cozy",
                "cinematic",
                "urban",
                "blue",
                "orange"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Rainy Window Café",
            image = R.drawable.rainy_nights_02,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "window",
                "cafe",
                "coffee",
                "night",
                "city",
                "lights",
                "cozy",
                "cat",
                "moon",
                "reflection",
                "wet street",
                "cinematic",
                "autumn"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Midnight Rain Drive",
            image = R.drawable.rainy_nights_03,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "car",
                "drive",
                "road",
                "mountains",
                "lake",
                "moon",
                "forest",
                "city lights",
                "reflection",
                "wet road",
                "cinematic",
                "autumn"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Rainy Lakeside Cabin",
            image = R.drawable.rainy_nights_04,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "cabin",
                "lake",
                "mountains",
                "moon",
                "forest",
                "boat",
                "dock",
                "lantern",
                "cozy",
                "reflection",
                "autumn",
                "cinematic"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Rainy Night Retreat",
            image = R.drawable.rainy_nights_05,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "city",
                "window",
                "cat",
                "book",
                "coffee",
                "cozy",
                "bedroom",
                "moon",
                "city lights",
                "reflection",
                "relaxing",
                "cinematic"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Rainy Mountain Escape",
            image = R.drawable.rainy_nights_06,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "mountains",
                "cabin",
                "lake",
                "moon",
                "hot tub",
                "terrace",
                "forest",
                "cozy",
                "luxury",
                "reflection",
                "mist",
                "cinematic"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Stormy Lighthouse",
            image = R.drawable.rainy_nights_07,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "lighthouse",
                "storm",
                "ocean",
                "sea",
                "waves",
                "lightning",
                "cliff",
                "rocks",
                "dramatic",
                "moody",
                "cinematic",
                "weather"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Midnight Rain Train",
            image = R.drawable.rainy_nights_08,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "train",
                "railway",
                "railroad",
                "mountains",
                "lake",
                "moon",
                "forest",
                "bridge",
                "mist",
                "reflection",
                "travel",
                "cinematic"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Rainy Lakeside Promenade",
            image = R.drawable.rainy_nights_09,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "lake",
                "promenade",
                "village",
                "mountains",
                "moon",
                "lights",
                "reflection",
                "cafe",
                "autumn",
                "cozy",
                "travel",
                "cinematic"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Rainy Glasshouse",
            image = R.drawable.rainy_nights_10,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "glasshouse",
                "greenhouse",
                "conservatory",
                "plants",
                "flowers",
                "garden",
                "moon",
                "cozy",
                "lanterns",
                "reflection",
                "romantic",
                "cinematic"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Midnight Rain Stop",
            image = R.drawable.rainy_nights_11,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "gas station",
                "road",
                "car",
                "mountains",
                "moon",
                "forest",
                "neon",
                "lights",
                "reflection",
                "road trip",
                "moody",
                "cinematic"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Tropical Rain Retreat",
            image = R.drawable.rainy_nights_12,
            category = "Nature",
            tags = listOf(
                "rain",
                "rainy",
                "night",
                "tropical",
                "beach",
                "hammock",
                "ocean",
                "island",
                "palms",
                "moon",
                "lanterns",
                "bungalow",
                "cozy",
                "relaxing",
                "paradise",
                "cinematic"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        )
    )
}