package com.example.wallora.repository.collections

import com.example.wallora.R
import com.example.wallora.model.Wallpaper

object RainbowChaosCollection {

    val wallpapers = listOf(

        Wallpaper(
            name = "Candy Capybara",
            image = R.drawable.rainbow_chaos_01,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "colorful",
                "candy",
                "capybara",
                "cute",
                "funny",
                "sweet",
                "donut",
                "gummy bears",
                "fantasy",
                "pink",
                "pastel",
                "kawaii",
                "magic",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Candy Dragon Splash",
            image = R.drawable.rainbow_chaos_02,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "colorful",
                "dragon",
                "cute",
                "candy",
                "gummy bears",
                "donut",
                "fantasy",
                "pink",
                "sweet",
                "kawaii",
                "castle",
                "waterfall",
                "magic",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Cosmic Candy Axolotl",
            image = R.drawable.rainbow_chaos_03,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "colorful",
                "axolotl",
                "space",
                "cosmic",
                "rocket",
                "candy",
                "gummy",
                "cute",
                "fantasy",
                "pink",
                "kawaii",
                "planets",
                "galaxy",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Candy Princess Cat",
            image = R.drawable.rainbow_chaos_04,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "colorful",
                "cat",
                "kitten",
                "princess",
                "candy",
                "cute",
                "sweet",
                "pink",
                "fantasy",
                "kawaii",
                "castle",
                "macarons",
                "lollipop",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Cotton Candy Panda",
            image = R.drawable.rainbow_chaos_05,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "colorful",
                "panda",
                "cotton candy",
                "candy",
                "cute",
                "sweet",
                "pink",
                "fantasy",
                "kawaii",
                "cake",
                "cupcake",
                "castle",
                "sprinkles",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Chocolate Zoomies",
            image = R.drawable.rainbow_chaos_06,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "colorful",
                "dog",
                "puppy",
                "cute",
                "funny",
                "chocolate",
                "whipped cream",
                "candy",
                "sweet",
                "butterflies",
                "strawberry",
                "cupcake",
                "fantasy",
                "kawaii",
                "running",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Candy Wave Bunny",
            image = R.drawable.candy_chaos_08,
            category = "Fantasy",
            tags = listOf(
                "bunny",
                "rabbit",
                "candy",
                "rainbow",
                "cute",
                "colorful",
                "sweet",
                "fantasy",
                "surfing",
                "candy world",
                "chocolate",
                "strawberry",
                "cupcake",
                "balloons",
                "funny",
                "kids",
                "kawaii"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Candy Cloud Fox",
            image = R.drawable.rainbow_chaos_07,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "colorful",
                "fox",
                "cute",
                "candy",
                "cotton candy",
                "lollipop",
                "butterflies",
                "sweet",
                "pink",
                "fantasy",
                "kawaii",
                "cloud",
                "magic",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Candy Coaster Panda",
            image = R.drawable.rainbow_chaos_09,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "colorful",
                "panda",
                "puppy",
                "bunny",
                "rollercoaster",
                "candy",
                "cute",
                "funny",
                "sweet",
                "pink",
                "fantasy",
                "kawaii",
                "balloons",
                "waterfall",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Candy River Otter",
            image = R.drawable.rainbow_chaos_10,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "colorful",
                "otter",
                "cute",
                "surfing",
                "candy",
                "cotton candy",
                "gummy fish",
                "gummy bears",
                "strawberry",
                "sweet",
                "fantasy",
                "kawaii",
                "waterfall",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Rainbow Slide Elephant",
            image = R.drawable.rainbow_chaos_11,
            category = "Animals",
            tags = listOf(
                "rainbow",
                "elephant",
                "cute",
                "ducklings",
                "candy",
                "colorful",
                "slide",
                "water",
                "splash",
                "sweet",
                "strawberry",
                "fantasy",
                "kawaii",
                "funny",
                "pink",
                "chaos"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        ),
        Wallpaper(
            name = "Candyland Party",
            image = R.drawable.candy_chaos_12,
            category = "Fantasy",
            tags = listOf(
                "candy",
                "candyland",
                "unicorn",
                "rainbow",
                "cute",
                "colorful",
                "fantasy",
                "kawaii",
                "animals",
                "penguin",
                "bunny",
                "dog",
                "sweets",
                "donut",
                "cotton candy",
                "funny",
                "magical",
                "pink"
            ),
            rating = 5.0,
            downloads = "0",
            badge = "NEW",
            isTopPick = true
        )
    )
}